#@ load("@ytt:data", "data")
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: #@ data.values.artifactId + "-apis"
  description: #@ "APIs published by the " +  data.values.artifactId + " component"
spec:
  type: openapi
  lifecycle: development
  owner: dekt-dev-team2
  system:  #@ data.values.parentApp
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: #@ data.values.artifactId + "-apis"
    servers:
      - url: mood-sensors.apps.dekt.io/v1
    paths:
      /activate:
        post:
          summary: activate a sensor
        tags:
            - sensors-update
      /measure:
        get:
          summary: retrieve all mood information
        tags:
            - sensors-reading
