#@ load("@ytt:data", "data") 
--- 
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    app.tanzu.vmware.com/workload-type: dekt-backend
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: #@ data.values.parentApp

spec:
  source:
    git:
      url: #@ "https://github.com/dektlong/" + data.values.artifactId
      ref:
        branch: dev
  
  #@ if data.values.addNosql or data.values.addMsg or data.values.addDB:
  serviceClaims:
    
    #@ if data.values.addDB:
    - name: #@ data.values.dbName
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: #@data.values.dbType + "-db"
    #@ end
    
    #@ if data.values.addMsg:
    - name: #@ data.values.msgName
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: #@ data.values.msgType + "-queue"
    #@ end
    
    #@ if data.values.addNosql:
    - name: #@ data.values.nosqlName
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: #@ data.values.nosqlType + "-datastore" 
     #@ end
  
  #@ end
