#@ load("@ytt:data", "data") 
---
applications:
- name: #@ data.values.artifactId
  path: ./build
  routes:
    - route: #@ data.values.artifactId + ".apps.internal"
  memory: 1G
  env:
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+}}'
    SPRING_PROFILES_ACTIVE: dev
#@ if data.values.addDB or data.values.addMsg or data.values.addCache: 
  service:
  #@ if data.values.addDB: 
    - #@ data.values.dbType + "-service"
  #@ end
  #@ if data.values.addMsg: 
    - #@ data.values.dbType + "-service"
  #@ end
  #@ if data.values.addCache:
    - #@ data.values.cacheType + "-service"
   #@ end
#@ end
