#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: #@ data.values.artifactId + "-routes"
spec:
  service: 
    name: #@ data.values.artifactId + "-service"
  routes:
    - predicates:
        - #@ "Path=/api/" + data.values.apiGroups[0]
        - Method=GET
      filters:
        - RateLimit=2,10s
      tags:
        - #@ data.values.apiGroups[0]
      title: "open api for read-only functionality"
      description: "open api for read only interactions with the backend service"
    - predicates:
        - #@ "Path=/api/" + data.values.apiGroups[0] + "/{" + data.values.apiGroups[0] + "Id}/" + data.values.apiGroups[0] + "-request"
        - Method=POST,PUT,DELETE
      filters:
        - CircuitBreaker="myCircuitBreaker,forward:/inCaseOfFailureUseThis"
      ssoEnabled: true
      tokenRelay: true
      tags:
        - #@ data.values.apiGroups[1]
      title: "SSO protected api for write functionality"
      description: "SSO protected api for write/delete/update interactions with the backend service"
      model:
        requestBody:
          description: #@ "Manage " + data.values.apiGroups[1]
          content:
            'application/json':
              schema:
                type: object
                description: #@ data.values.apiGroups[1] + " schema"
                properties:
                  itemName:
                    type: string
                  description:
                    type: string
                    format: email
                  notes:
                    type: string
                required: [ "name", "description" ]
