#@ load("@ytt:data", "data") 
--- 
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    app.tanzu.vmware.com/workload-type: web-backend

spec:
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: main
#@ if data.values.addDataEntity:
  serviceClaims:
  #@ if data.values.entityType == "rabbitmq":
    - name: rabbitmq-service
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name:  #@ data.values.entityName
  #@ else
    - name: #@ data.values.entityType
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: #@ data.values.entityType
        name:  #@ data.values.entityName
  #@ end
#@ end
