#@ load("@ytt:data", "data") 
--- 
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    app.tanzu.vmware.com/workload-type: online-store

spec:
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: "dev"
#@ if data.values.addDataEntity:
  services:
    - apiVersion: services.tanzu.vmware.com/v1alpha1
      kind: #@ data.values.entityType
#@ end
    params:
    - name: java-version
      value: #@ data.values.javaVersion
#@ if data.values.javaDebug:
    - name: debug
      value: true
#@ end
