#@ load("@ytt:data", "data") 
--- 
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    app.tanzu.vmware.com/workload-type: stream

spec:
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: main
#@ if data.values.addDB or data.values.addMsg or data.values.addCache: 
  serviceClaims:
  #@ if data.values.addDB: 
    - name: #@ data.values.dbType + "-claim"
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: #@ data.values.dbType 
        name: #@ data.values.dbName
  #@ end
  #@ if data.values.addMsg: 
    - name: #@ data.values.msgType + "-claim"
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: #@ data.values.msgType
        name: #@ data.values.msgName
  #@ end
  #@ if data.values.addCache:
    - name: #@ data.values.cacheType + "-claim"
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: #@ data.values.cacheType
        name: #@ data.values.cacheName
  #@ end
#@ end
    
