#@ load("@ytt:data", "data") 
--- 
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    app.tanzu.vmware.com/workload-type: web-backend

spec:
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: main
  serviceClaims:
    - name: #@ data.values.dbType + "-claim"
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: a-type
        name:  a-name
    - name: b-claim
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: a-type
        name:  a-name
    - name: c-claim
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: a-type
        name:  a-name
    
