#@ load("@ytt:data", "data")
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: #@ data.values.artifactId + "-apis"
  description: #@ "APIs published by the " +  data.values.artifactId + " component"
spec:
  type: #@ data.values.apiType
  lifecycle: development
  owner: #@ data.values.apiOwner
  system:  #@ data.values.parentApp
  definition: 
    $text: config/tap/apis
